version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=your-database-host
      - DB_PORT=5432
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password
    volumes:
      - .:/var/www/html
